package vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;


public class AgenteDetectorGUI extends javax.swing.JFrame {

    public AgenteDetectorGUI() {
        initComponents();
        adjustImage();
        setLocationRelativeTo(null);
        
    }
    
    private void adjustImage(){
//        ImageIcon originalImage = new ImageIcon(getClass().getResource("/images/faceDetecting.gif"));
        ImageIcon originalImage = new ImageIcon(getClass().getResource("/images/mentors-group.png"));
        Image newImage = originalImage.getImage().getScaledInstance(
                this.lblDetectingImage.getWidth(), this.lblDetectingImage.getHeight(), 
                Image.SCALE_DEFAULT);
        Icon newIcon = new ImageIcon(newImage);
        this.lblDetectingImage.setIcon(newIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblDectecting = new javax.swing.JLabel();
        lblDetectingImage = new javax.swing.JLabel();
        comboBoxEmotions = new javax.swing.JComboBox<>();
        buttonSend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDectecting.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblDectecting.setText("Agente Detector");
        lblDectecting.setAlignmentX(1.0F);
        jPanel3.add(lblDectecting, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 190, 40));
        jPanel3.add(lblDetectingImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 750, 420));

        comboBoxEmotions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alegría", "Enojo", "Aburrimiento", "Miedo", "Interés" }));
        jPanel3.add(comboBoxEmotions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 530, 40));

        buttonSend.setText("Enviar");
        buttonSend.setAlignmentY(0.4F);
        buttonSend.setIconTextGap(3);
        buttonSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSendMouseClicked(evt);
            }
        });
        buttonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 210, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSendActionPerformed

    private void buttonSendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSendMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSendMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgenteDetectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgenteDetectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgenteDetectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgenteDetectorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgenteDetectorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton buttonSend;
    public javax.swing.JComboBox<String> comboBoxEmotions;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDectecting;
    private javax.swing.JLabel lblDetectingImage;
    // End of variables declaration//GEN-END:variables
}